Repository sealsystems/node-log-metadata-plossys, pull requests merged in 2022-09, with the labels that each got.

#225 Update build configuration
  package-lock.json
Labels: automatic-merge

#226 Update build configuration
  package-lock.json
Labels: automatic-merge

#227 Update build configuration
  package-lock.json
Labels: automatic-merge

#228 Update build configuration
  package-lock.json
Labels: automatic-merge

#229 Update build configuration
  package-lock.json
Labels: automatic-merge

#230 Update build configuration
  package-lock.json
Labels: automatic-merge

#231 feat: get jobId from _id
  lib/inspect.js
  test/inspectTest.js
Labels: release/minor, release/feat

#232 Update build configuration
  package-lock.json
Labels: automatic-merge

#233 fix: do not error here on jobs without jobId
  lib/inspect.js
Labels: release/patch, release/fix

#234 Update build configuration
  package-lock.json
Labels: automatic-merge

#235 Update build configuration
  package-lock.json
Labels: automatic-merge

#236 feat: if no _id is present, try id
  lib/inspect.js
  test/inspectTest.js
Labels: release/minor, release/feat

#237 Update build configuration
  package-lock.json
Labels: automatic-merge

#238 Update build configuration
  package-lock.json
Labels: automatic-merge

#239 Update build configuration
  package-lock.json
Labels: automatic-merge

#240 Update build configuration
  package-lock.json
Labels: automatic-merge

#241 Update build configuration
  package-lock.json
Labels: automatic-merge

#242 Update build configuration
  package-lock.json
Labels: automatic-merge

#243 Update build configuration
  .github/workflows/publish-on-npmjs-org.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/update-build-config.yml
  .nvmrc
  package-lock.json
Labels: automatic-merge

#244 Update build configuration
  package-lock.json
Labels: automatic-merge

#245 Update build configuration
  package-lock.json
Labels: automatic-merge

#246 Update build configuration
  package-lock.json
Labels: automatic-merge

#247 Update build configuration
  package-lock.json
Labels: automatic-merge

#248 Update build configuration
  package-lock.json
Labels: automatic-merge

#249 Update build configuration
  package-lock.json
Labels: automatic-merge

#250 Update build configuration
  package-lock.json
Labels: automatic-merge

#251 Update build configuration
  package-lock.json
Labels: automatic-merge
